// constants.js

export const FETCHING_INVOICES = 'FETCHING_INVOICEs'
export const FETCHING_INVOICEs_SUCCESS = 'FETCHING_INVOICEs_SUCCESS'
export const FETCHING_INVOICEs_FAILURE = 'FETCHING_INVOICEs_FAILURE'
