// constants.js

export const FETCHING_INVOICES = 'FETCHING_INVOICES'
export const FETCHING_INVOICES_SUCCESS = 'FETCHING_INVOICES_SUCCESS'
export const FETCHING_INVOICES_FAILURE = 'FETCHING_INVOICES_FAILURE'

export const FETCHING_COMPANIES= 'FETCHING_COMPANIES'
export const FETCHING_COMPANIES_SUCCESS = 'FETCHING_COMPANIES_SUCCESS'
export const FETCHING_COMPANIES_FAILURE = 'FETCHING_COMPANIES_FAILURE'
