// constants.js

export const FETCHING_INVOICES = 'FETCHING_INVOICES'
export const FETCHING_INVOICES_SUCCESS = 'FETCHING_INVOICES_SUCCESS'
export const FETCHING_INVOICESnp_FAILURE = 'FETCHING_INVOICES_FAILURE'
